spring:
  application:
    name: my-local-diary
  config:
    import: classpath:secret.properties
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/my_local_diary
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

## S3
cloud:
  aws:
    credentials:
      access-key: your-access-key
      secret-key: your-secret-key
    region:
      static: ap-northeast-2  # 서울 리전이면 이렇게
    s3:
      bucket: your-bucket-name