server:
  port: 8080

spring:
  application:
    name: my-local-diary
  config:
    import: classpath:secret.properties
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://host.docker.internal:3306/my_local_diary
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  profiles:
    include: jwt, aws
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.leesang.mylocaldiary.common.typehandler

token:
  secret: ${secret_key}
  access_expiration_time: 36000000      # Access Token: 15분 (900,000ms)
  refresh_expiration_time: 604800000  # Refresh Token: 7일 (604,800,000ms)

cloud:
  aws:
    s3:
      bucket: my-local-diary-prod
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2  # 서울
    stack:
      auto: false


kakao:
  client_id: ${REST_API_KEY}
  redirect_uri: http://localhost:8080/callback

logging:
  level:
    org.springframework.security: DEBUG

