server:
  port: 8080

spring:
  application:
    name: my-local-diary
  config:
    import: classpath:secret.properties
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/my_local_diary
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  profiles:
    include: jwt, aws
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

token:
  secret: ${secret_key}
  expiration_time: 43200000

cloud:
  aws:
    s3:
      bucket: my-local-diary-prod
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2  # 서울
    stack:
      auto: false

